channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3
  - bs4
  - cartopy
  - dask
  - fiona
  - geopandas
  - gmt
  - ipykernel
  - joblib
  - jupyter
  - lxml
  - matplotlib
  - moviepy
  - netcdf4
  - numpy<2.2  # required by pulearn
  - pandas
  - papermill
  - pip
  - plate-model-manager
  - pooch
  - pygplates
  - pykdtree
  - pyrolite
  - pyyaml
  - rasterio
  - requests
  - rioxarray
  - ruamel.yaml
  - scikit-image
  - scikit-learn<1.6  # required by pulearn
  - scipy<1.15
  - setuptools<81
  - shapely
  - six>=1.16,<1.17  # required by pulearn
  - stripy
  - tqdm
  - xarray
  - py-xgboost
  - pip:
    - PlateTectonicTools
    - pulearn
    - "git+https://github.com/cpalfonso/gplately.git@teeth-updates"
    - "git+https://github.com/brmather/Slab-Dip.git@main"
