channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3
  - cartopy
  - dask
  - dask-ml
  - geopandas
  - ipykernel
  - joblib
  - jupyter
  - matplotlib
  - moviepy
  - netcdf4
  - numpy
  - pandas
  - papermill
  - pip
  - plate-model-manager
  - pooch
  - pygplates
  - pykdtree
  - pyrolite
  - pyyaml
  - rasterio
  - requests
  - rioxarray
  - scikit-image
  # - scikit-learn=1.2.0
  - scikit-learn
  - scipy
  - shapely
  - six
  - stripy
  - tqdm
  - xarray
  - py-xgboost
  - pip:
    - PlateTectonicTools
    - "git+https://github.com/pulearn/pulearn.git@master"
    - "git+https://github.com/GPlates/gplately.git@subduction-teeth"
    - "git+https://github.com/brmather/Slab-Dip.git@main"
